COMMON_SRC="../Common/Variables.hpp"
MODEL_SRC="../Models/Logger.hpp"
SOCKET_SRC="../Sockets/SocketService.hpp"

all: ../Common/Variables.hpp ../Sockets/SocketService.hpp #$(COMMON_SRC) ${MODEL_SRC} ${SOCKET_SRC}
	g++ -o service main.cpp